azd env set AZURE_STORAGE_CONTAINER $env:AZURE_STORAGE_CONTAINER
azd env set AZURE_SEARCH_SERVICE $env:AZURE_SEARCH_SERVICE           
azd env set AZURE_SEARCH_INDEX $env:AZURE_SEARCH_INDEX             
azd env set AZURE_OPENAI_SERVICE $env:AZURE_OPENAI_SERVICE           
azd env set AZURE_OPENAI_GPT_DEPLOYMENT $env:AZURE_OPENAI_GPT_DEPLOYMENT
azd env set AZURE_OPENAI_CHATGPT_DEPLOYMENT $env:AZURE_OPENAI_CHATGPT_DEPLOYMENT
azd env set AZURE_OPENAI_CHATGPT_MODEL $env:AZURE_OPENAI_CHATGPT_MODEL
azd env set AZURE_FORMRECOGNIZER_SERVICE $env:AZURE_FORMRECOGNIZER_SERVICE
azd env set search_query_key $env:search_query_key
azd env set formrecognizerkey $env:form_recognizer_key     
azd env set storagekey $env:azure_storage_key

$Env:AZURE_STORAGE_CONTAINER=$env:AZURE_STORAGE_CONTAINER
$Env:AZURE_SEARCH_SERVICE=$env:AZURE_SEARCH_SERVICE           
$Env:AZURE_SEARCH_INDEX=$env:AZURE_SEARCH_INDEX             
$Env:AZURE_OPENAI_SERVICE=$env:AZURE_OPENAI_SERVICE           
$Env:AZURE_OPENAI_GPT_DEPLOYMENT=$env:AZURE_OPENAI_GPT_DEPLOYMENT
$Env:AZURE_OPENAI_CHATGPT_DEPLOYMENT=$env:AZURE_OPENAI_CHATGPT_DEPLOYMENT
$Env:AZURE_OPENAI_CHATGPT_MODEL=$env:AZURE_OPENAI_CHATGPT_MODEL
$Env:AZURE_FORMRECOGNIZER_SERVICE=$env:AZURE_FORMRECOGNIZER_SERVICE
$Env:search_query_key=$env:search_query_key
$Env:formrecognizerkey=$env:form_recognizer_key     
$Env:storagekey=$env:azure_storage_key